fn_list_testPatches = {...
    'test/patches/bmc_po_75_no25.jpg',...
    'test/patches/borough.jpg',...
    'test/patches/cel.jpg',...
    'test/patches/colchester.jpg',...
    'test/patches/costa.jpg',...
    'test/patches/de_britains.jpg',...
    'test/patches/flats.jpg',...
    'test/patches/it.jpg',...
    'test/patches/litter.jpg',...
    'test/patches/teeth.jpg',...
    'test/patches/times.jpg',...
    'test/patches/zanussi.jpg'};