
function out = proj_0221_single(stage, cmd1)

PROJ_NAME = '20130218';

CHAR_REGION_FILENAME = 'ft_vector_7feat_20130217';

NON_CHAR_REGION_FOLDERNAME = '0218_test3_nonc_mat';
NON_CHAR_REGION_RANDOM_SEED = PROJ_NAME;
NON_CHAR_REGION_NO = 50;
NON_CHAR_REGION_RESIZE = [200,200];

% general rules
RULES.MIN_W_ABS = 3;
RULES.MIN_H_ABS = 3;
RULES.MIN_SIZE = 30;
RULES.MIN_W_REG2IMG_RATIO = 0.0019;
RULES.MAX_W_REG2IMG_RATIO = 0.4562;
RULES.MIN_H_REG2IMG_RATIO = 0.0100;
RULES.MAX_H_REG2IMG_RATIO = 0.7989;
RULES.PROB_MIN = 0.2;
RULES.DELTA_MIN = 0.1;
RULES.MIN_CONSEQ_ER_LEVEL = 2;

input = 2;
switch input
    case 1
        TEST_IMG_FOLDER = '../../../Codes/_input_files';
        TEST_IMG_FILENAME = 'IMG_1291.JPG';
    case 2
        TEST_IMG_FOLDER = 'ryoungt_05.08.2002';
        TEST_IMG_FILENAME = 'bPICT0009.JPG';
    case 3
        TEST_IMG_FOLDER = 'ryoungt_05.08.2002';
        TEST_IMG_FILENAME = 'Pict0003.jpg';
end
TEST_IMG_RESIZE = [200,200];
addpath_for_me;

switch stage
    case 1
        % extract char features
        text_detect_a1_ftExtract_Chars74K_char( ...
            CHAR_REGION_FILENAME);
    case 2
        % extract non-char features
        text_detect_a1_ftExtract_ICDAR2003_general( ...
            0, 0, RULES, ...
            NON_CHAR_REGION_FOLDERNAME, ...
            {NON_CHAR_REGION_NO, ...
             NON_CHAR_REGION_RANDOM_SEED, ...
             NON_CHAR_REGION_RESIZE}, ...
            cmd1);
    case 3
        % check progress of stage 2
        out = text_detect_h1_checkProgress( ...
            0, ...
            NON_CHAR_REGION_FOLDERNAME, ...
            {NON_CHAR_REGION_NO, ...
             NON_CHAR_REGION_RANDOM_SEED, ...
             NON_CHAR_REGION_RESIZE});
    case 4
        % collect and train for 1st/2nd stage classifier
        text_detect_a2_ftCol( ...
            CHAR_REGION_FILENAME, ...
            NON_CHAR_REGION_FOLDERNAME, ...
            NON_CHAR_REGION_RESIZE, ...
            PROJ_NAME);
    case 5
        % 1st stage classifier, and save postprob
        text_detect_a3_calAdaPostp( ...
            TEST_IMG_FOLDER, ...
            TEST_IMG_FILENAME, ...
            TEST_IMG_RESIZE, ...
            PROJ_NAME, ...
            RULES);
    case 61
        % prune by (1)Adaboost postprob, and (2) SVM(optional) - Algo1
        text_detect_a4_classifyAdaPostp_optSVM_algo1( ...
            TEST_IMG_FOLDER, ...
            TEST_IMG_FILENAME, ...
            TEST_IMG_RESIZE, ...
            PROJ_NAME, ...
            RULES, ...
            cmd1);
    case 62
        % prune by (1)Adaboost postprob, and (2) SVM(optional) - Algo2
        text_detect_a4_classifyAdaPostp_optSVM_algo2( ...
            TEST_IMG_FOLDER, ...
            TEST_IMG_FILENAME, ...
            TEST_IMG_RESIZE, ...
            PROJ_NAME, ...
            RULES, ...
            cmd1);
    case 63
        % same as 61
%         % prune by (1)Adaboost postprob, and (2) SVM(optional) - Algo3
%         text_detect_a4_classifyAdaPostp_optSVM_algo3( ...
%             TEST_IMG_FOLDER, ...
%             TEST_IMG_FILENAME, ...
%             TEST_IMG_RESIZE, ...
%             PROJ_NAME, ...
%             RULES, ...
%             cmd1);
    case 64
        % prune by (1)Adaboost postprob, and (2) SVM(optional) - Algo3
        text_detect_a4_classifyAdaPostp_optSVM_algo4( ...
            TEST_IMG_FOLDER, ...
            TEST_IMG_FILENAME, ...
            TEST_IMG_RESIZE, ...
            PROJ_NAME, ...
            RULES, ...
            cmd1);
    case 65
        % prune by (1)Adaboost postprob, and (2) SVM(optional) - Algo3
        text_detect_a4_classifyAdaPostp_optSVM_algo5( ...
            TEST_IMG_FOLDER, ...
            TEST_IMG_FILENAME, i, ...
            TEST_IMG_RESIZE, ...
            PROJ_NAME, ...
            RULES, ...
            cmd1);
end

end